set_property IOSTANDARD LVCMOS33 [get_ports fpga_rst]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_clk]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]

set_property PACKAGE_PIN U4 [get_ports start_pg]
set_property PACKAGE_PIN P17 [get_ports fpga_clk]
set_property PACKAGE_PIN R15 [get_ports fpga_rst]

set_property PACKAGE_PIN B4 [get_ports {seg_out0[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out0[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out0[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out0[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out0[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out0[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out0[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out0[0]}]

set_property PACKAGE_PIN D4 [get_ports {seg_out1[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_out1[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_out1[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_out1[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_out1[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_out1[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_out1[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_out1[0]}]

set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]

set_property PACKAGE_PIN K2 [get_ports test_wire]
set_property IOSTANDARD LVCMOS33 [get_ports test_wire]

set_property PACKAGE_PIN K1 [get_ports clock_led]
set_property IOSTANDARD LVCMOS33 [get_ports clock_led]

