# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/User/Desktop/SEU_CSE_507_user_uart_bmpg_1.3 [current_project]
set_property ip_output_repo {c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/prgmip32.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/new/ALU.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/BCD_ctrl.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/BCD_to_Cathodes.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/new/IFetc32.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/anode_ctrl.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/binary_BCD.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/clock_divider_mileage.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/new/controller.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/new/decoder.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/refreshcounter.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/seven_seg_controller.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/sevseg/top_mileage.v}
  {C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/new/CPU_TOP.v}
}
read_ip -quiet {{C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/cpuclk/cpuclk.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/cpuclk/cpuclk.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc}}]

read_ip -quiet {{C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/prgrom/prgrom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/constrs_1/new/cons.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/User/Desktop/Computer organization/CPU Project/CPU_Project/CPU.srcs/constrs_1/new/cons.xdc}}]


synth_design -top CPU_TOP -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_TOP_utilization_synth.rpt -pb CPU_TOP_utilization_synth.pb"
